services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: weather-app
    ports:
      - "8081:80"
    depends_on:
      - backend
