services:
  promocode-factory-api:
    image: ghcr.io/alex-makhina/promo-code-factory-app:latest
    container_name: 'promocode-factory-api'
    restart: always
    ports:
      - "8091:8080"
    volumes:
      - db:/app/db
    environment:
      - "ConnectionStrings:PromocodeFactoryDb=Filename=/app/db/PromoCodeFactoryDb.sqlite"
      - "ASPNETCORE_ENVIRONMENT=Development"
      
volumes:
  db: